signupとfooterの作成
Yuseidosukoiya/frontend-basic-site pull request #3
Opened 2023-11-03 10:06 UTC by Yuseidosukoiya

2023-11-03 15:30 UTC, moe-backend commented
signup-descriptionの始まりの位置がsignup-form-labelと揃っているようにしましょう！

2023-11-04 02:15 UTC, higashiji2000 requested changes
![スクリーンショット 2023-11-04 11 08 27](https://github.com/Yuseidosukoiya/frontend-basic-site/assets/83479175/58bce9f0-8f29-41cf-b23b-5f68ac9024a1)
![スクリーンショット 2023-11-04 11 07 40](https://github.com/Yuseidosukoiya/frontend-basic-site/assets/83479175/a589762c-368c-4b7f-bf07-9d05adea2f54)
Figmaと比べて、フォームと上の説明文の始点が揃っていないのでご確認お願いします！

2023-11-04 02:15 UTC, higashiji2000 commented on index.html
> +    </section>
```suggestion
    <footer class="footer">
      <p class="footer-copyright">©2023 GrandPlayers</p>
    </footer>
```
footerタグを使ってもいいかもですね！
https://developer.mozilla.org/ja/docs/Web/HTML/Element/footer

2023-11-04 02:15 UTC, higashiji2000 commented on ctyle.css
> +}
共通化を考えられているのめちゃくちゃ素晴らしいです！！！

2023-11-04 02:15 UTC, higashiji2000 commented on index.html
> +        <div class="button" id="courses-button">
```suggestion
        <div class="button courses-button">
```
idを使うと詳細度が上がってしまうので、別のスタイルを当てたい場合はこのように2つ目のクラスを指定するのが良いかなと思います。
ただ現状 `couses-button` に対してはスタイルが当たっていないと思うので、そもそもなくしてしまっても良いかもしれません。

2023-11-05 03:32 UTC, higashiji2000 requested changes
![image](https://github.com/Yuseidosukoiya/frontend-basic-site/assets/83479175/75eef64d-b327-40d7-b803-0ded00eb7f26)

- 左に寄っている
- ボタンの影が見えない

2点修正お願いします！

2023-11-05 17:14 UTC, higashiji2000 requested changes
![image](https://github.com/Yuseidosukoiya/frontend-basic-site/assets/83479175/6e71f4f7-0632-4744-abe8-ff5c86bc9c3a)

750 ~ 800px でレイアウト崩れが発生しています。
これは、 `about-section-body` 等いくつかの部分で `width: 800px` と固定値にしていることが原因で発生しているものです。
[お手本](https://shinonome.io/frontend-basic-2023-html-css-assignment-baseline/)も参考にしつつ、画面幅が狭くなったらいい感じに収縮するようなCSSを実装してみてください。

過去の範囲の修正も必要になってくると思います。
当時指摘できずすみませんが、確認お願いします:pray:

2023-11-06 09:34 UTC, higashiji2000 approved these changes
LGTM✨

2023-11-06 20:47 UTC, merged